apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  sources: 
    repoURL: https://github.com/kbaras2020/projetosd23.git
    targetRevision: HEAD
    path: k3sconfig
    repoURL: https://github.com/kbaras2020/sd1.git
    targetRevision: HEAD
    path: k3sconfig
  destination:
    server: https://kubernetes.default.svc
    namespace: testes
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
    automated:
      selfHeal: true
      prune: true
