apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sge-grupo2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cesar02dd/SD.git
    targetRevision: HEAD
    path: k8s-configuration
  destination: 
    server: https://kubernetes.default.svc
    namespace: sge
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
    automated:
      selfHeal: true
      prune: true
