apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eventos
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/filipe942/SD_BackendGrupo5.git
    targetRevision: HEAD
    path: k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: sge

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
    
    automated:
      selfHeal: true
      prune: true
